name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # 외부 테스트 DB를 사용하므로 services 블록은 생략합니다.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests on External Test DB
        env:
          PORT: ${{ secrets.DB_PORT }}
          DB_PORT: 3306
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DB_HOST: 35.232.176.120
          DB_USER: root
          DB_PASSWORD: test
          FRONTEND: ${{ secrets.FRONTEND }}
          FE_LOCAL: ${{ secrets.FE_LOCAL }}
        run: npm test

